"""empty message

Revision ID: 7c6525086f62
Revises: 
Create Date: 2026-01-18 15:24:51.431513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6525086f62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.Column('ano_compra', sa.Integer(), nullable=False),
    sa.Column('sequencial_compra', sa.Integer(), nullable=False),
    sa.Column('numero_compra', sa.String(), nullable=False),
    sa.Column('processo', sa.String(), nullable=False),
    sa.Column('objeto_compra', sa.Text(), nullable=False),
    sa.Column('valor_total_homologado', sa.Float(), nullable=True),
    sa.Column('srp', sa.Boolean(), nullable=False),
    sa.Column('data_inclusao', sa.DateTime(), nullable=False),
    sa.Column('data_abertura_proposta', sa.DateTime(), nullable=False),
    sa.Column('data_encerramento_proposta', sa.DateTime(), nullable=False),
    sa.Column('data_publicacao_pncp', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao_global', sa.DateTime(), nullable=False),
    sa.Column('numero_controle_pncp', sa.String(), nullable=False),
    sa.Column('modalidade_id', sa.Integer(), nullable=False),
    sa.Column('modo_disputa_id', sa.Integer(), nullable=False),
    sa.Column('valor_total_estimado', sa.Float(), nullable=False),
    sa.Column('modalidade_nome', sa.String(), nullable=False),
    sa.Column('modo_disputa_nome', sa.String(), nullable=False),
    sa.Column('tipo_instrumento_convocatorio_codigo', sa.Integer(), nullable=False),
    sa.Column('tipo_instrumento_convocatorio_nome', sa.String(), nullable=False),
    sa.Column('situacao_compra_id', sa.Integer(), nullable=False),
    sa.Column('situacao_compra_nome', sa.String(), nullable=False),
    sa.Column('usuario_nome', sa.String(), nullable=False),
    sa.Column('orgao_sub_rogado', sa.String(), nullable=True),
    sa.Column('unidade_sub_rogada', sa.String(), nullable=True),
    sa.Column('informacao_complementar', sa.Text(), nullable=True),
    sa.Column('link_sistema_origem', sa.String(), nullable=True),
    sa.Column('justificativa_presencial', sa.Text(), nullable=True),
    sa.Column('link_processo_eletronico', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amparo_legal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orgao_entidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('poder_id', sa.String(), nullable=False),
    sa.Column('esfera_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidade_orgao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('uf_nome', sa.String(), nullable=False),
    sa.Column('codigo_unidade', sa.String(), nullable=False),
    sa.Column('uf_sigla', sa.String(), nullable=False),
    sa.Column('municipio_nome', sa.String(), nullable=False),
    sa.Column('nome_unidade', sa.String(), nullable=False),
    sa.Column('codigo_ibge', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unidade_orgao')
    op.drop_table('orgao_entidade')
    op.drop_table('amparo_legal')
    op.drop_table('compra')
    # ### end Alembic commands ###
